- hosts: vps
  become: true
  become_user: root
  tasks:
    - name: get service facts
      ansible.builtin.service_facts:

    - name: try to work out how to access the service
      ansible.builtin.debug:
        var: ansible_facts.services["webmin.service"]
