- hosts: vps
  become: true
  become_user: root
  tasks:
    - name: "Webmin test result"
      debug: 
        msg: "Webmin found"
      when: "'webmin' in ansible_facts.packages"

    - name: "Webmin test result"
      debug: 
        msg: "Webmin NOT found"
      when: "'webmin' not in ansible_facts.packages"
