- hosts: vps
  become: true
  become_user: root
  tasks:
    - name: "Webmin test result"
      command: systemctl status webmin
      ignore_errors: yes
      changed_when: false
      register: service_webmin_status
