h
#
# Example Usage:
# [user@host ~$] ansible-playbook /etc/ansible/playbooks/webmin.yml --extra-vars 'target=nameFromHostsFile'
#
#vars:
#  pkgs:
#    - perl
#    - libnet-ssleay-perl
#    - openssl
#    - libauthen-pam-perl
#    - libpam-runtime
#    - libio-pty-perl
#    - apt-show-versions
#    - python

- hosts: 10.0.2.3
  become: true
  become_user: root
  tasks:
    - name: Install multiple packages
      apt: name={{ item }} state=latest update_cache=true
      loop: [git, wget, unzip, curl, perl, libnet-ssleay-perl, openssl, libauthen-pam-perl, libpam-runtime, libio-pty-perl, apt-show-versions, python3 ]
    
    - name: Run 
      ansible.builtin.shell:
        cmd: curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh | sh setup-repos.sh -- -y
        
    #- name: Webmin Repositors Donwload/Setup
    #  command: 'curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh', 'sh setup-repos.sh'
      
    - name: Webmin (Application Installing
      apt: name=webmin state=latest update_cache=true
     
