
#
# Example Usage:
# [user@host ~$] ansible-playbook /etc/ansible/playbooks/webmin.yml --extra-vars 'target=nameFromHostsFile'
#
- hosts: '10.0.2.3'
  become: true
  become_user: root

  tasks:
    - name: Install Webmin and prerequisites
      become: yes
      package:
        name:
          - perl
          - libnet-ssleay-perl
          - openssl
          - libauthen-pam-perl
          - libpam-runtime
          - libio-pty-perl
          - apt-show-versions
          - python
        status: present
        
         
