#
# Example Usage:
# [user@host ~$] ansible-playbook /etc/ansible/playbooks/webmin.yml --extra-vars 'target=nameFromHostsFile'
#
#vars:
#  pkgs:
#    - perl
#    - libnet-ssleay-perl
#    - openssl
#    - libauthen-pam-perl
#    - libpam-runtime
#    - libio-pty-perl
#    - apt-show-versions
#    - python
---
- name: Update Zabbix repo and Agent2
  hosts: 10.0.2.3
  become: yes
  tasks:
    - name: Install multiple packages
      apt: name={{ item }} state=latest update_cache=true
      loop: [git, wget, unzip, curl, perl, libnet-ssleay-perl, openssl, libauthen-pam-perl, libpam-runtime, libio-pty-perl, apt-show-versions, python3 ]
    
    - name: Download Wget
      ansible.builtin.get_url:
        url: https://sourceforge.net/projects/webadmin/files/webmin/2.202/webmin_2.202_all.deb/download
        dest: /tmp/
    
    - name: fetch package
      get_url:
        url: https://sourceforge.net/projects/webadmin/files/webmin/2.202/webmin_2.202_all.deb/download
        dest: /tmp/
     
    - name: install package
      become: true
      apt:
        deb: /tmp/webmin_2.202_all.deb
      
    
    #- name: Run 
    #  ansible.builtin.shell:
    #    cmd: wget https://sourceforge.net/projects/webadmin/files/webmin/2.202/webmin_2.202_all.deb/download && apt install --install-recommends ./webmin_2.202_all.deb
        
    #- name: Webmin Repositors Donwload/Setup
    #  command: 'curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh', 'sh setup-repos.sh'
      
    - name: Webmin (Application Installing
      apt: name=webmin state=latest update_cache=true
     
