---
- name: Update Zabbix repo and Agent2
  hosts: 10.0.2.2
  become: yes
  #become_method: sudo
  tasks:
    # Get distrib version for good repo
    #- name: Distribution
    #  debug: msg="{{ ansible_distribution }}"
    #- name: Distribution version
    #  debug: msg="{{ ansible_distribution_version}}"
    - name: Distribution major version
      debug: msg="{{ ansible_distribution_major_version }}"
    #- name: Show facts available on the system
    #  ansible.builtin.debug:
    #    var: ansible_facts

    # Ubuntu 24
    - name: Install last deb for update repo
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu24.04_all.deb
        allow_downgrade: yes
      when: 
        - ansible_facts['distribution_major_version'] == "24"

    # Ubuntu 22
    - name: Install last deb for update repo
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu22.04_all.deb
        allow_downgrade: yes
      when: 
        - ansible_facts['distribution_major_version'] == "22"

    # Ubuntu 20
    - name: Install last deb for update repo
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu20.04_all.deb
        allow_downgrade: yes
      when: 
        - ansible_facts['distribution_major_version'] == "20"

    # Ubuntu 18
    - name: Install last deb for update repo
      ansible.builtin.apt:
        deb: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu18.04_all.deb
        allow_downgrade: yes
      when: 
        - ansible_facts['distribution_major_version'] == "18"

    # Check if Zabbix is present
    - name: Check if Zabbix is present
      stat: 
        path: /etc/zabbix/zabbix_agent2.conf
      register: zabbix_config_file

    # Write message if Zabbix is presnet
    - name: Zabbix agent is present
      debug: 
        msg: "Zabbix Agent is installed !"
      when: zabbix_config_file.stat.exists
      
    - name: Install Software Package
      apt:
        name:
          - zabbix-agent2
        state: present
        update_cache: yes
    
    - name: Configure the Zabbix agent
      replace:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: '{{item.regexp}}'
        replace: '{{item.replace}}'
      with_items:
        - {regexp: "^Server=127.0.0.1$", replace: "Server={{zabbix_server}}"}
        - {regexp: "^ServerActive=127.0.0.1$", replace: "ServerActive={{zabbix_server}}"}
        - {regexp: "^Hostname=Zabbix server$", replace: "Hostname={{ansible_hostname}}"}
        - {regexp: "^# ListenPort=10050$", replace: "ListenPort=10050"}
        - {regexp: "^# ListenIP=0.0.0.0$", replace: "ListenIP=0.0.0.0"}
        - {regexp: "^# SourceIP=$", replace: "SourceIP={{ansible_hostname}}"}
      vars:
        - zabbix_server: zabbix-server

    - name: Start the Zabbix agent service
      service:
        name: zabbix-agent2
        state: started
        enabled: yes

