---
- hosts: proxmox
  become: true
  become_user: root
  tasks:
    - name: Update all packages to their latest version
        ansible.builtin.apt:
        name: "*"
        state: latest

    - name: Upgrade the OS (apt-get dist-upgrade)
        ansible.builtin.apt:
        upgrade: dist
