---
- name: Update Zabbix repo and Agent2
  hosts: 192.168.1.121
  become: yes
  #become_method: sudo
  tasks:
    # Get distrib version for good repo
    #
    #- name: Distribution
    #  debug: msg="{{ ansible_distribution }}"
    - name: Distribution version
      debug: msg="{{ ansible_distribution_version}}"
    #- name: Distribution major version
    #  debug: msg="{{ ansible_distribution_major_version }}"
    #- name: Show facts available on the system
    #  ansible.builtin.debug:
    #    var: ansible_facts