---
- name: Install Software Packages
  hosts: 10.0.2.3
  become: yes
  tasks:
    - name: Install Software Package
      apt:
        name:
          - zabbix-agent
        state: present
        update_cache: yes
#- name: Install the Zabbix agent
#  yum:
#    name: http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-agent-3.4.8-1.el7.x86_64.rpm
    - name: Configure the Zabbix agent
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '{{item.regexp}}'
        replace: '{{item.replace}}'
      with_items:
        - {regexp: "^Server=127.0.0.1$", replace: "Server={{zabbix_server}}"}
        - {regexp: "^ServerActive=127.0.0.1$", replace: "ServerActive={{zabbix_server}}"}
        - {regexp: "^Hostname=Zabbix server$", replace: "Hostname={{ansible_hostname}}"}
        - {regexp: "^# ListenPort=10050$", replace: "ListenPort=10050"}
        - {regexp: "^# ListenIP=0.0.0.0$", replace: "ListenIP=0.0.0.0"}
      vars:
        - zabbix_server: zabbix.lcl.jrlmo.us
    - name: Start the Zabbix agent service
      service:
        name: zabbix-agent
        state: started
        enabled: yes
    - name: Allow everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: allow
    - name: Allow port range 10050-10051
      community.general.ufw:
        rule: allow
        port: 10050:10051
        proto: tcp
        
#- name: Create a new host or update an existing host's info
#  local_action:
#    module: zabbix_host
#    server_url: http://zabbix-server.brazilsouth.cloudapp.azure.com
#    login_user: zabbix-admin
#    login_password: zabbix-admin-password
#    host_name: '{{ansible_hostname}}'
#    host_groups:
#      - Virtual machines
#      - Azure - Cluster Kubernetes
#    link_templates:
#      - Template OS Linux
#      - Template App Docker
#    interfaces:
#      - type: 1
#        main: 1
#        useip: 1
#        ip: '{{ansible_ssh_host}}'
#        dns: ""
#        port: 10050
